### ISSUE TITLE
RuntimeError: Format is invalid: csmsc_009901 csmsc_009901 0.285

### ISSUE THREAD

**Issue by wuhaobest1** [kan-bayashi/ParallelWaveGAN#105]
Traceback (most recent call last):
  File "/home/data/xfding/miniconda3/envs/env_tts/bin/parallel-wavegan-preprocess", line 11, in <module>
    load_entry_point('parallel-wavegan==0.3.4', 'console_scripts', 'parallel-wavegan-preprocess')()
  File "/home/data/xfding/miniconda3/envs/env_tts/lib/python3.7/site-packages/parallel_wavegan-0.3.4-py3.7.egg/parallel_wavegan/bin/preprocess.py", line 119, in main
  File "/home/data/xfding/miniconda3/envs/env_tts/lib/python3.7/site-packages/parallel_wavegan-0.3.4-py3.7.egg/parallel_wavegan/datasets/scp_dataset.py", line 155, in __init__
  File "/home/data/xfding/miniconda3/envs/env_tts/lib/python3.7/site-packages/kaldiio-2.15.1-py3.7.egg/kaldiio/matio.py", line 62, in load_scp
  File "/home/data/xfding/miniconda3/envs/env_tts/lib/python3.7/site-packages/kaldiio-2.15.1-py3.7.egg/kaldiio/matio.py", line 145, in __init__

I have this problem, anyone can help me ? thx

**Comment by wuhaobest1** [comment]
when I run the script run.sh, this error block the train process.

**Comment by kan-bayashi** [comment]
It seems that `segments` file is broken.
Could you attach the `segments` file in `data` directory?

**Comment by kan-bayashi** [comment]
It should be like:

```bash
$ cd egs/csmsc/voc1
$ cat data/eval/segments
csmsc_009901 csmsc_009901 0.285 4.786776870232002
csmsc_009902 csmsc_009902 0.2826883264869545 4.1216585751960295
csmsc_009903 csmsc_009903 0.2653709343118607 4.405920090876146
csmsc_009904 csmsc_009904 0.29503646459377986 4.750414171220013
csmsc_009905 csmsc_009905 0.27745996046355925 4.356669999043448
csmsc_009906 csmsc_009906 0.2703383555142324 4.22
csmsc_009907 csmsc_009907 0.26486263857658976 4.61263040151721
csmsc_009908 csmsc_009908 0.2586152269960104 4.280014947046968
csmsc_009909 csmsc_009909 0.26450786853322217 4.503091181158041
csmsc_009910 csmsc_009910 0.27908856915808533 4.168477829743123
csmsc_009911 csmsc_009911 0.2936401758739642 4.4476959407612355
csmsc_009912 csmsc_009912 0.2718421875298321 4.330555403922323
csmsc_009913 csmsc_009913 0.2692359683039362 4.933186824022859
csmsc_009914 csmsc_009914 0.2900117074285866 4.139818509318559
csmsc_009915 csmsc_009915 0.29 4.530823695929089
csmsc_009916 csmsc_009916 0.31381502486373586 4.459275758773387
csmsc_009917 csmsc_009917 0.27539016330153404 4.082332625259784
csmsc_009918 csmsc_009918 0.295 4.9187833225690944
csmsc_009919 csmsc_009919 0.26478168993460555 5.440852883103411
csmsc_009920 csmsc_009920 0.26185707732089136 6.388835238010591
csmsc_009921 csmsc_009921 0.2536285160575048 6.961250142431758
csmsc_009922 csmsc_009922 0.292114391165968 6.865
csmsc_009923 csmsc_009923 0.22094034329481166 3.4814564898802285
csmsc_009924 csmsc_009924 0.27247121270143737 3.9415700638143782
csmsc_009925 csmsc_009925 0.2865966684277073 3.51
csmsc_009926 csmsc_009926 0.2647468586668209 3.601135332397818
csmsc_009927 csmsc_009927 0.2669432491758855 4.036460954493885
csmsc_009928 csmsc_009928 0.2889050088655588 3.700677455045362
csmsc_009929 csmsc_009929 0.2859512754238101 3.4655856043952733
csmsc_009930 csmsc_009930 0.2941748544876404 3.877693460875024
csmsc_009931 csmsc_009931 0.27825294325784017 3.5903989093612796
csmsc_009932 csmsc_009932 0.2764936714267941 3.769740781019383
csmsc_009933 csmsc_009933 0.29 3.704048730095618
csmsc_009934 csmsc_009934 0.29670556003126697 3.8382363051549175
csmsc_009935 csmsc_009935 0.2921395207025224 3.5068285216345516
csmsc_009936 csmsc_009936 0.2943350319188431 3.6380203211042965
csmsc_009937 csmsc_009937 0.2717928120970167 3.919954967441342
csmsc_009938 csmsc_009938 0.3105044004926019 3.989722916071616
csmsc_009939 csmsc_009939 0.28945006471781215 3.7307344071486375
csmsc_009940 csmsc_009940 0.2881153264971323 3.591898484260124
csmsc_009941 csmsc_009941 0.3026495334352567 4.035846254914458
csmsc_009942 csmsc_009942 0.26869483213093026 4.015634851965346
csmsc_009943 csmsc_009943 0.29376892165356006 3.795
csmsc_009944 csmsc_009944 0.295 3.7500905285951682
csmsc_009945 csmsc_009945 0.30240915459229006 3.8945124277742855
csmsc_009946 csmsc_009946 0.28754805369125796 4.406628154378371
csmsc_009947 csmsc_009947 0.28155204622148194 3.707502987539725
csmsc_009948 csmsc_009948 0.2951957593737802 3.4075136298753206
csmsc_009949 csmsc_009949 0.29015069610008504 3.701192537562445
csmsc_009950 csmsc_009950 0.2881493260908892 3.9385341177301787
csmsc_009951 csmsc_009951 0.30412425659943265 3.7843491905897317
csmsc_009952 csmsc_009952 0.265 3.8761759634431683
csmsc_009953 csmsc_009953 0.2965725734965577 3.7492228101815925
csmsc_009954 csmsc_009954 0.2912273744779339 3.824723496074873
csmsc_009955 csmsc_009955 0.26611215596286275 3.4976014426804856
csmsc_009956 csmsc_009956 0.28125961936679633 5.030820641419309
csmsc_009957 csmsc_009957 0.2685173250102742 5.699916026660744
csmsc_009958 csmsc_009958 0.27695610955476324 6.359324626667514
csmsc_009959 csmsc_009959 0.27741123459016354 5.225
csmsc_009960 csmsc_009960 0.2984275793755409 4.4644417800901675
csmsc_009961 csmsc_009961 0.3120753119696911 3.5599507089096236
csmsc_009962 csmsc_009962 0.305 4.718553307643643
csmsc_009963 csmsc_009963 0.29309863345701237 4.368482190161578
csmsc_009964 csmsc_009964 0.3 4.270044279475048
csmsc_009965 csmsc_009965 0.2782896378908 4.624512298386696
csmsc_009966 csmsc_009966 0.3086761594559932 4.4154457860051375
csmsc_009967 csmsc_009967 0.28628594021147213 5.966289879124873
csmsc_009968 csmsc_009968 0.295 3.0576372155534353
csmsc_009969 csmsc_009969 0.2941296213548898 3.094059665274941
csmsc_009970 csmsc_009970 0.28903370220554403 4.469040290296376
csmsc_009971 csmsc_009971 0.2606596115832721 3.9393907751579973
csmsc_009972 csmsc_009972 0.2907408481639675 3.88
csmsc_009973 csmsc_009973 0.26022011482817947 3.9279706668940406
csmsc_009974 csmsc_009974 0.2762246616901881 6.115425570722121
csmsc_009975 csmsc_009975 0.304600196191655 6.952677451489761
csmsc_009976 csmsc_009976 0.26538659793555136 4.92958211705904
csmsc_009977 csmsc_009977 0.27557600117108083 3.7713923242345495
csmsc_009978 csmsc_009978 0.2813790623718798 3.560768306980935
csmsc_009979 csmsc_009979 0.2788109762033194 3.6914900439655485
csmsc_009980 csmsc_009980 0.29315846040202087 3.2524147561927586
csmsc_009981 csmsc_009981 0.27393481626033667 3.17031989833768
csmsc_009982 csmsc_009982 0.28944510968691217 3.85
csmsc_009983 csmsc_009983 0.28276730485752816 3.393190208630863
csmsc_009984 csmsc_009984 0.2780556492803696 3.6179519451518343
csmsc_009985 csmsc_009985 0.2983962713493582 3.141911676122565
csmsc_009986 csmsc_009986 0.27030029897958446 3.656779921207429
csmsc_009987 csmsc_009987 0.2880535777440909 3.4192298729538706
csmsc_009988 csmsc_009988 0.29203890080612377 3.2545332771043354
csmsc_009989 csmsc_009989 0.28832899797294875 6.821975674094592
csmsc_009990 csmsc_009990 0.2720305714156325 3.326809634675825
csmsc_009991 csmsc_009991 0.2784619622000457 5.547803254397521
csmsc_009992 csmsc_009992 0.29626297712661104 5.51791962193831
csmsc_009993 csmsc_009993 0.29970828354381274 5.7504907995429235
csmsc_009994 csmsc_009994 0.2811937727718327 5.868726115714699
csmsc_009995 csmsc_009995 0.28340244556868266 5.638135937367717
csmsc_009996 csmsc_009996 0.29198340629103864 5.453233442242207
csmsc_009997 csmsc_009997 0.28078332961183067 6.064608098075352
csmsc_009998 csmsc_009998 0.2701042383096932 5.815095199743006
csmsc_009999 csmsc_009999 0.30020272567476214 4.339711376651835
csmsc_010000 csmsc_010000 0.29371906536735565 4.245240559593412
```

**Comment by kan-bayashi** [comment]
I tested with the current master but I could not reproduce the issue.

**Comment by kan-bayashi** [comment]
For safety, I added more checks in csmsc recipe (#107).
If you still have the problem, please re-open this issue.

**Comment by wuhaobest1** [comment]
this issue cause I didn't install the nkf tool, and the data_download.sh script exec not right. thanks for replay.
