### ISSUE TITLE
AssertionError 

### ISSUE THREAD

**Issue by 943274923** [kan-bayashi/ParallelWaveGAN#146]
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/data/ParallelWaveGAN/tools/venv/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/data/ParallelWaveGAN/tools/venv/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/data/ParallelWaveGAN/parallel_wavegan/bin/train.py", line 513, in __call__
    self._check_length(x, c, self.hop_size, 0)
  File "/data/ParallelWaveGAN/parallel_wavegan/bin/train.py", line 556, in _check_length
    assert len(x) == (len(c) - 2 * context_window) * hop_size
AssertionError

I change config as:
hop_size: 200
upsample_scales: [5, 4, 2, 5]

**Comment by kan-bayashi** [comment]
Maybe you changed the setting after feature extraction.
