### ISSUE TITLE
Multiple GPUs

### ISSUE THREAD

**Issue by RuslanSel** [kan-bayashi/ParallelWaveGAN#172]
ljspeech/run.sh with ngpu=8 gives
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/parallel-wavegan-train", line 11, in <module>
    load_entry_point('parallel-wavegan', 'console_scripts', 'parallel-wavegan-train')()
  File "/home/ubuntu/tts/ParallelWaveGAN/parallel_wavegan/bin/train.py", line 775, in main
    shuffle=True,
TypeError: __init__() got an unexpected keyword argument 'shuffle'
Thanks in advance.

**Comment by kan-bayashi** [comment]
Maybe your pytorch version is old.
Please try pytorch >= 1.2.

**Comment by RuslanSel** [comment]
Yes. Pytorch is old.
Thanks.
