### ISSUE TITLE
run.pl: job failed, log is in exp/*

### ISSUE THREAD

**Issue by Alexey322** [kan-bayashi/ParallelWaveGAN#176]
Hello. I followed the two steps(stage 0 and stage 1) to prepare the dataset, but at the stage of training the network when run ./run.sh --stage 2 --stop_stage 2 I get an error. Here is the error log:
 
[train]:   0%|          | 0/2000000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "Z:\Soft\Python3.6.7\Scripts\parallel-wavegan-train-script.py", line 33, in <module>
    sys.exit(load_entry_point('parallel-wavegan', 'console_scripts', 'parallel-wavegan-train')())
  File "z:\soft\parallelwavegan\parallel_wavegan\bin\train.py", line 911, in main
    trainer.run()
  File "z:\soft\parallelwavegan\parallel_wavegan\bin\train.py", line 89, in run
    self._train_epoch()
  File "z:\soft\parallelwavegan\parallel_wavegan\bin\train.py", line 287, in _train_epoch
    for train_steps_per_epoch, batch in enumerate(self.data_loader["train"], 1):
  File "z:\soft\python3.6.7\lib\site-packages\torch\utils\data\dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "z:\soft\python3.6.7\lib\site-packages\torch\utils\data\dataloader.py", line 682, in __init__
    w.start()
  File "z:\soft\python3.6.7\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "z:\soft\python3.6.7\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "z:\soft\python3.6.7\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "z:\soft\python3.6.7\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "z:\soft\python3.6.7\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'main.<locals>.<lambda>'

[train]:   0%|          | 0/2000000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "z:\soft\python3.6.7\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "z:\soft\python3.6.7\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
ain:695) INFO: lambda_feat_match = 25.0

Could you please help me?

**Comment by kan-bayashi** [comment]
Did you use windows? It seems that lambda functions cannot pickled in Windows.
I've never used Windows environment and do not want to deal with Windows-specific issues.
But you can try to change `num_workers=0` in training conf.

**Comment by Alexey322** [comment]
> 
> 
> Did you use windows? It seems that lambda functions cannot pickled in Windows.
> I've never used Windows environment and do not want to deal with Windows-specific issues.
> But you can try to change `num_workers=0` in training conf.

Thanks a lot, its working
