### ISSUE TITLE
cannot resume from checkpoint

### ISSUE THREAD

**Issue by xxoospring** [kan-bayashi/ParallelWaveGAN#182]
I use customize dataset training, but I cant resume from checpoint, this is my cmd line as egs/readme says:
```
./run.sh --stage 2 --resume exp/train_nodev_YuanXi_Base_multi_band_melgan.v2/checkpoint-750000steps.pkl
```
and it reports:
```
Stage 2: Network training
Training start. See the progress via exp/train_nodev_YuanXi_Base_multi_band_melgan.v2/train.log.
run.pl: job failed, log is in exp/train_nodev_YuanXi_Base_multi_band_melgan.v2/train.log

```

**Comment by kan-bayashi** [comment]
Please show the log.

**Comment by xxoospring** [comment]
> Please show the log.
```
Traceback (most recent call last):
  File "/root/anaconda3/bin/parallel-wavegan-train", line 11, in <module>
    load_entry_point('parallel-wavegan', 'console_scripts', 'parallel-wavegan-train')()
  File "/workspace/proj/ParallelWaveGAN/parallel_wavegan/bin/train.py", line 722, in main
    allow_cache=config.get("allow_cache", False),  # keep compatibility
  File "/workspace/proj/ParallelWaveGAN/parallel_wavegan/datasets/audio_mel_dataset.py", line 63, in __init__
    mel_lengths = [mel_load_fn(f).shape[0] for f in mel_files]
  File "/workspace/proj/ParallelWaveGAN/parallel_wavegan/datasets/audio_mel_dataset.py", line 63, in <listcomp>
    mel_lengths = [mel_load_fn(f).shape[0] for f in mel_files]
  File "/workspace/proj/ParallelWaveGAN/parallel_wavegan/bin/train.py", line 707, in <lambda>
    mel_load_fn = lambda x: read_hdf5(x, "feats")  # NOQA
  File "/workspace/proj/ParallelWaveGAN/parallel_wavegan/utils/utils.py", line 54, in read_hdf5
    hdf5_file = h5py.File(hdf5_name, "r")
  File "/root/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/root/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (file signature not found)

```

**Comment by xxoospring** [comment]
> It seems the log clearly says it is not related to `resume` function but your `hdf5` file is corrupt.
> Please check the feature files are valid.

but it seems "stats.h5" was generated by run.sh. I check feature files and I resume training from stage 2 which should not related feature file

**Comment by xxoospring** [comment]
> `stats.h5` is not used during training.
> So the feature file may contain some errors.

I start training from strach again now.

**Comment by xxoospring** [comment]
I'm sorry  for my misoperation of run command line. I used "CUDA_VISIABLE_DEVICES=0 ./run.sh", but when I restore training from checkpoint, I start training used "./run.sh", That the reason.
