### ISSUE TITLE
failed to execute run.sh

### ISSUE THREAD

**Issue by wizardk** [kan-bayashi/ParallelWaveGAN#219]
./run.sh
Stage 0: Data preparation
Successfully split data directory.
Successfully split data directory.
Successfully prepared data.
Stage 1: Feature extraction
Feature extraction start. See the progress via dump/train_nodev/raw/preprocessing.*.log.
Feature extraction start. See the progress via dump/dev/raw/preprocessing.*.log.
Feature extraction start. See the progress via dump/eval/raw/preprocessing.*.log.
Successfully make subsets.
Successfully make subsets.
Successfully make subsets.
run.pl: 4 / 4 failed, log is in dump/dev/raw/preprocessing.*.log
run.pl: 4 / 4 failed, log is in dump/train_nodev/raw/preprocessing.*.log
run.pl: 4 / 4 failed, log is in dump/eval/raw/preprocessing.*.log
./run.sh: 3 background jobs are failed.

In the log file:
Traceback (most recent call last):
  File "/root/anaconda3/bin/parallel-wavegan-preprocess", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/root/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/root/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/root/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/root/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/root/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'parallel-wavegan' distribution was not found and is required by the application

@kan-bayashi Do you know why and how can I fix it? Thanks.

**Comment by kan-bayashi** [comment]
How did you install this repository?
Did you follow the instruction?

**Comment by wizardk** [comment]
@kan-bayashi Thanks for your help. It's totally my fault. The reason of this error is that I changed the fold name after run 'pip install -e .'
