### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by capavrulus** [kan-bayashi/ParallelWaveGAN#224]
After I tried to use PyTorch 1.6.0, I got this error when training after 7k steps. 

  File "/home/train/.local/bin/parallel-wavegan-train", line 11, in <module>
    load_entry_point('parallel-wavegan', 'console_scripts', 'parallel-wavegan-train')()
  File "/home/train/ParallelWaveGAN/parallel_wavegan/bin/train.py", line 922, in main
    trainer.run()
  File "/home/train/ParallelWaveGAN/parallel_wavegan/bin/train.py", line 91, in run
    self._train_epoch()
  File "/home/train/ParallelWaveGAN/parallel_wavegan/bin/train.py", line 290, in _train_epoch
    for train_steps_per_epoch, batch in enumerate(self.data_loader["train"], 1):
  File "/home/train/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/train/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/train/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/train/.local/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
ConnectionResetError: Caught ConnectionResetError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/train/.local/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/train/.local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/train/.local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/train/ParallelWaveGAN/parallel_wavegan/datasets/audio_mel_dataset.py", line 104, in __getitem__
    if self.allow_cache and len(self.caches[idx]) != 0:
  File "<string>", line 2, in __getitem__
  File "/opt/anaconda3/lib/python3.7/multiprocessing/managers.py", line 819, in _callmethod
    kind, result = conn.recv()
  File "/opt/anaconda3/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/opt/anaconda3/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/opt/anaconda3/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by capavrulus** [comment]
Changed the number of workers to 0, waiting to see if it fixes the problem.

**Comment by kan-bayashi** [comment]
How large is your dataset and cpu memory?
In default setting, we cache the all of dataset on the cpu memory, so I’m wondering this error caused by OOM of CPU memory.

**Comment by kan-bayashi** [comment]
Related: https://github.com/pytorch/pytorch/issues/9127

**Comment by capavrulus** [comment]
> Related: [pytorch/pytorch#9127](https://github.com/pytorch/pytorch/issues/9127)

@kan-bayashi  How do you fix this? I got the same error when it's around 7k iterations, even the worker number is already set to 0.

My pytorch version is 1.6.0, what version did you use to successfully train the vocoder?

**Comment by capavrulus** [comment]
[train]:   2%|▏         | 7693/400000 [1:52:40<8774:43:44, 80.52s/it]Traceback (most recent call last):
  File "/home/train/.local/bin/parallel-wavegan-train", line 11, in <module>
    load_entry_point('parallel-wavegan', 'console_scripts', 'parallel-wavegan-train')()
  File "/home/train/ParallelWaveGAN/parallel_wavegan/bin/train.py", line 922, in main
    trainer.run()
  File "/home/train/ParallelWaveGAN/parallel_wavegan/bin/train.py", line 91, in run
    self._train_epoch()
  File "/home/train/ParallelWaveGAN/parallel_wavegan/bin/train.py", line 290, in _train_epoch
    for train_steps_per_epoch, batch in enumerate(self.data_loader["train"], 1):
  File "/home/train/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/train/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 403, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/train/.local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/train/.local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/train/ParallelWaveGAN/parallel_wavegan/datasets/audio_mel_dataset.py", line 104, in __getitem__
    if self.allow_cache and len(self.caches[idx]) != 0:
  File "<string>", line 2, in __getitem__
  File "/opt/anaconda3/lib/python3.7/multiprocessing/managers.py", line 819, in _callmethod
    kind, result = conn.recv()
  File "/opt/anaconda3/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/opt/anaconda3/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/opt/anaconda3/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

I have no idea how this error could persist even though the number of workers is already 0. Why does it call "multiprocessing.py" with no parallel worker?

**Comment by kan-bayashi** [comment]
Actually, I’ve never met this error and it seems pytorch problem. So I have no idea to avoid this error.
I used 1.4 or 1.5

**Comment by kan-bayashi** [comment]
Hmm. Please try allow_cache=False.

**Comment by capavrulus** [comment]
> How large is your dataset and cpu memory?
> In default setting, we cache the all of dataset on the cpu memory, so I’m wondering this error caused by OOM of CPU memory.

My dataset is around 184G (dump folder size), and my machine RAM is around 50G.

> Actually, I’ve never met this error and it seems pytorch problem. So I have no idea to avoid this error.
> I used 1.4 or 1.5

Can you provide the exact version number you used that have successfully trained the model? Which pytorch version should I use? 1.4 or 1.5?

**Comment by kan-bayashi** [comment]
In my case, both 1.4 and 1.5 works.

> My dataset is around 184G (dump folder size), and my machine RAM is around 50G.

Then, the problem is `allow_cache`.
If you set `allow_cache=True`, the training is cached on your memory.
In your case, your dataset size is bigger than the CPU memory size.
Therefore, the above error might have happened.
Please try `allow_cache: false`.

**Comment by kan-bayashi** [comment]
If you have a still problem, please re-open.
