### ISSUE TITLE
Error when fine-tuing PWG vocoder

### ISSUE THREAD

**Issue by ymzlygw** [kan-bayashi/ParallelWaveGAN#262]
Hi, I want to finetune the PWG vocoder with my own single-spk dataset(130 utt only). I have follow the https://github.com/kan-bayashi/ParallelWaveGAN/tree/master/egs, and finished my own recipe.  I use the pretrain model:[jsut_parallel_wavegan.v1]. 
But when i run, when stage 2 starts, the error occurs and message is follows:

run.pl: job failed, log is in exp/train_nodev_parallel_wavegan.v1_PWG_pretrain/train.log. And message is train.log is 

Traceback (most recent call last):
  File "/root/anaconda3/envs/pwg/bin/parallel-wavegan-train", line 33, in <module>
    sys.exit(load_entry_point('parallel-wavegan', 'console_scripts', 'parallel-wavegan-train')())
  File "/root/AI_/ParallelWaveGAN/parallel_wavegan/bin/train.py", line 911, in main
    trainer.load_checkpoint(args.pretrain, load_only_params=True)
  File "/root/AI_/ParallelWaveGAN/parallel_wavegan/bin/train.py", line 147, in load_checkpoint
    self.model["generator"].load_state_dict(state_dict["model"]["generator"])
  File "/root/anaconda3/envs/pwg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ParallelWaveGANGenerator:
	size mismatch for upsample_net.upsample.up_layers.3.weight_v: copying a param with shape torch.Size([1, 1, 1, 11]) from checkpoint, the shape in current model is torch.Size([1, 1, 1, 9]).
	size mismatch for upsample_net.upsample.up_layers.5.weight_v: copying a param with shape torch.Size([1, 1, 1, 7]) from checkpoint, the shape in current model is torch.Size([1, 1, 1, 9]).
	size mismatch for upsample_net.upsample.up_layers.7.weight_v: copying a param with shape torch.Size([1, 1, 1, 11]) from checkpoint, the shape in current model is torch.Size([1, 1, 1, 9]).
# Accounting: time=4 threads=1

In con/parallel_wavegan.v1.yaml , I just change the sample rate to 24000 which is same as my wav file's sr.
Is there anything wrong? Thanks a lot for your help!

**Comment by ymzlygw** [comment]
Sorry for my stupid error. I just find that I use the template config rather than download's PWG pretrained model's config. Not only sr param is different. So I change the config and start training successfullly! 

Thanks, i'll close this issue.
