### ISSUE TITLE
How to modify the sampling rate when use csmsc dataset to train the vocoder?

### ISSUE THREAD

**Issue by Hu-chengyang** [kan-bayashi/ParallelWaveGAN#359]
Dear professor:
I try to train a vocoder, and I have installed parallelwavegan,and I run the command: run.sh,however it came out with the traceback:
Traceback (most recent call last):
File "/home/liyp/anaconda3/envs/xll/bin/parallel-wavegan-preprocess", line 11, in
load_entry_point('parallel-wavegan', 'console_scripts', 'parallel-wavegan-preprocess')()
File "/data2/hcy/VQMIVC-main/vocoder/ParallelWaveGAN/parallel_wavegan/bin/preprocess.py", line 186, in main
), f"{utt_id} seems to have a different sampling rate."

I find that the sampling rate of csmsc is 24000hz,however the sampling rate of the my model is 16000,could you tell me how to modify the sampling rate?

**Comment by kan-bayashi** [comment]
Please change here
https://github.com/kan-bayashi/ParallelWaveGAN/blob/1f1f6750ea09ee416496eba79ec1a21dc20e5daf/egs/csmsc/voc1/local/data_prep.sh#L9
And launch the recipe from data prep.

**Comment by Hu-chengyang** [comment]
Thank you.

**Comment by Hu-chengyang** [comment]
However,the new problem comes out:
2022-05-11 19:50:59,583 (utils:95) ERROR: There is no such a hdf5 file (dump/train_nodev/stats.(grep -q hdf5 <(yq .format /data2/hcy/VQMIVC-main/ParallelWaveGAN/egs/csmsc/voc1/conf/parallel_wavegan.v3.yaml) && echo h5 || echo npy)).

**Comment by Hu-chengyang** [comment]
Yes,I modified it as :stats_ext=$"(grep -q "hdf5" <(yq ".format" "${conf}") && echo "h5" || echo "npy")"
Because it came out with:syntax error near unexpected token `('

**Comment by Hu-chengyang** [comment]
How can I solve this problem?

**Comment by kan-bayashi** [comment]
That is wrong. Please use it as is.

**Comment by kan-bayashi** [comment]
If you are not familiar with shellscript, please use hard coding.
E.g, stats_ext=h5

**Comment by Hu-chengyang** [comment]
Do you mean modify the "stats_ext=$(grep -q "hdf5" <(yq ".format" "${conf}") && echo "h5" || echo "npy") " as "stats_ext=h5"?

**Comment by kan-bayashi** [comment]
right

**Comment by Hu-chengyang** [comment]
Thank you, I will try.

**Comment by Hu-chengyang** [comment]
How to stop the training?
