### ISSUE TITLE
 kaldiio loading flac failed

### ISSUE THREAD

**Issue by Jackiexiao** [kan-bayashi/ParallelWaveGAN#372]
I follow instruction here to use pre-extract feature to train vocoder : 

https://github.com/kan-bayashi/ParallelWaveGAN/blob/master/egs/README.md#run-training-using-espnet2-tts-recipe-within-5-minutes

txt2mel training works well, but  kaldiio loading flac is failed, when I download and listening to this `jenny-standard-1.flac` audio, it sounds normal.... maybe it's cause by some weird audio format issue?

### logs
```
  2 # Started at Fri Jun 10 09:56:00 UTC 2022
  3 #
  4 ^M  0%|          | 0/6147 [00:00<?, ?it/s]/data1/jackie/anaconda3/envs/espnet/lib/python3.8/site-packages/kaldiio/utils.py:482: UserWarning: An error happens at loading "dump/raw/org/tr_no_dev/data/format.1/data_wav/jenny-standard-1.flac"
  5   warnings.warn('An error happens at loading "{}"'.format(ark_name))
  6 ^M  0%|          | 0/6147 [00:00<?, ?it/s]
  7 Traceback (most recent call last):
  8   File "/data1/jackie/anaconda3/envs/espnet/bin/parallel-wavegan-preprocess", line 33, in <module>
  9     sys.exit(load_entry_point('parallel-wavegan', 'console_scripts', 'parallel-wavegan-preprocess')())
 10   File "/data2/jackie/company/tts/pwg-vocoder/parallel_wavegan/bin/preprocess.py", line 192, in main
 11     for utt_id, (audio, fs) in tqdm(dataset):
 12   File "/data1/jackie/anaconda3/envs/espnet/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
 13     for obj in iterable:
 14   File "/data2/jackie/company/tts/pwg-vocoder/parallel_wavegan/datasets/scp_dataset.py", line 245, in __getitem__
 15     fs, audio = self.audio_loader[utt_id]
 16   File "/data1/jackie/anaconda3/envs/espnet/lib/python3.8/site-packages/kaldiio/utils.py", line 480, in __getitem__
 17     return self._loader(ark_name)
 18   File "/data1/jackie/anaconda3/envs/espnet/lib/python3.8/site-packages/kaldiio/matio.py", line 241, in load_mat
 19     return _load_mat(fd, offset, slices, endian=endian)
 20   File "/data1/jackie/anaconda3/envs/espnet/lib/python3.8/site-packages/kaldiio/matio.py", line 331, in _load_mat
 21     array = read_kaldi(fd, endian)
 22   File "/data1/jackie/anaconda3/envs/espnet/lib/python3.8/site-packages/kaldiio/matio.py", line 441, in read_kaldi
 23     array = read_ascii_mat(fd)
 24   File "/data1/jackie/anaconda3/envs/espnet/lib/python3.8/site-packages/kaldiio/matio.py", line 588, in read_ascii_mat
 25     char = fd.read(1).decode(encoding=default_encoding)
 26 UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 0: unexpected end of data
 27 # Accounting: time=4 threads=1
 28 # Ended (code 1) at Fri Jun 10 09:56:04 UTC 2022, elapsed time 4 seconds
~                                                                            
```

**Comment by Jackiexiao** [comment]
never mind, I prepare data from scratch
