### ISSUE TITLE
with nvidia 2070 8gb ,RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by ohadianoush** [kan-bayashi/ParallelWaveGAN#68]
i use LJSpeech with defult config . 
i see this in config:
# This configuration requires 12 GB GPU memory and takes ~3 days on TITAN V.
and i want know how i can change config file for my 8gb gpu.

[train]:   0%|          | 0/400000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/usr/local/bin/parallel-wavegan-train", line 11, in <module>
    load_entry_point('parallel-wavegan', 'console_scripts', 'parallel-wavegan-train')()
  File "/home/ai/ParallelWaveGAN/parallel_wavegan/bin/train.py", line 671, in main
    trainer.run()
  File "/home/ai/ParallelWaveGAN/parallel_wavegan/bin/train.py", line 87, in run
    self._train_epoch()
  File "/home/ai/ParallelWaveGAN/parallel_wavegan/bin/train.py", line 212, in _train_epoch
    self._train_step(batch)
  File "/home/ai/ParallelWaveGAN/parallel_wavegan/bin/train.py", line 159, in _train_step
    y_ = self.model["generator"](*x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ai/ParallelWaveGAN/parallel_wavegan/models/parallel_wavegan.py", line 151, in forward
    x, h = f(x, c)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ai/ParallelWaveGAN/parallel_wavegan/layers/residual_block.py", line 119, in forward
    xa, xb = xa + ca, xb + cb

RuntimeError: CUDA out of memory. Tried to allocate 38.00 MiB (GPU 0; 7.79 GiB total capacity; 6.65 GiB already allocated; 37.31 MiB free; 6.67 GiB reserved in total by PyTorch)

**Comment by kan-bayashi** [comment]
You can change batch size and batch max steps to be smaller.
https://github.com/kan-bayashi/ParallelWaveGAN/blob/af12f91f788538a1ced7be1b10211af4ba09576b/egs/ljspeech/voc1/conf/parallel_wavegan.v1.yaml#L81-L82
